import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/globals/ThemeProvider";
import { Toaster } from "@/components/ui/sonner"
import { Fragment } from 'react'
import Plausible from "@/components/globals/Plausible";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.className} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system">
                    <Fragment>
                        {children}
                        <Toaster/>
                    </Fragment>
                </ThemeProvider>
                <Plausible />
            </body>
        </html>
    );
}
